/**
 * Frontend API Integration Layer
 * Connects UI to Google Apps Script Blockchain Backend
 */

const API_BASE_URL = "https://script.google.com/macros/s/AKfycbxleqW0AX_7mMh9P2q0hR5dYT3-XtgIPN0-hb48Nhblca0bUBuIeUyJwMvGmw35xwrF1Q/exec";

// --- 1. Teacher Portal: Issue Single Certificate ---
const issueForm = document.getElementById("issueCertForm");
if (issueForm) {
    issueForm.addEventListener("submit", async function(e) {
        e.preventDefault();

        const submitBtn = issueForm.querySelector("button[type='submit']");
        const originalText = submitBtn.textContent;
        submitBtn.textContent = "Mining Block & Storing...";
        submitBtn.disabled = true;

        const payload = {
            studentName: document.getElementById("student-name").value.trim(),
            enrollmentNo: document.getElementById("enrollment-no").value.trim(),
            courseDept: document.getElementById("dept").value.trim(),
            eventTitle: document.getElementById("cert-type").value.trim(),
            certId: "" // Auto-generated by backend if empty
        };

        try {
            // Text/plain mode bypasses CORS preflight in Apps Script
            const response = await fetch(API_BASE_URL, {
                method: "POST",
                headers: { "Content-Type": "text/plain;charset=utf-8" },
                body: JSON.stringify(payload)
            });

            const data = await response.json();

            if (data.status === "SUCCESS") {
                alert(`Certificate Issued Successfully!\n\nCertificate ID: ${data.certId}\nBlock Index: #${data.blockIndex}\nHash: ${data.currentHash.substring(0, 16)}...`);
                issueForm.reset();
            } else {
                alert("Failed to issue certificate: " + (data.message || "Unknown error"));
            }
        } catch (error) {
            console.error("API Error:", error);
            alert("Error connecting to Blockchain Ledger. Check console.");
        } finally {
            submitBtn.textContent = originalText;
            submitBtn.disabled = false;
        }
    });
}

// --- 2. Public Verification Portal: Real-time Check ---
const verifyForm = document.getElementById("verifyForm");
const resultBox = document.getElementById("verificationResult");

if (verifyForm) {
    verifyForm.addEventListener("submit", async function(e) {
        e.preventDefault();

        const certIdInput = document.getElementById("cert-id");
        const queryVal = certIdInput.value.trim();
        const submitBtn = verifyForm.querySelector("button[type='submit']");

        if (!queryVal) return;

        submitBtn.textContent = "Verifying Ledger...";
        submitBtn.disabled = true;

        try {
            const response = await fetch(`${API_BASE_URL}?action=verify&query=${encodeURIComponent(queryVal)}`);
            const data = await response.json();

            if (data.status === "SUCCESS" && data.record) {
                const rec = data.record;
                
                // Show result container if present in DOM
                if (resultBox) {
                    resultBox.style.display = "block";
                    
                    const elName = document.getElementById("resStudentName");
                    const elEnroll = document.getElementById("resEnrollment");
                    const elCertId = document.getElementById("resCertId");
                    const elEvent = document.getElementById("resCategory");
                    const elDate = document.getElementById("resIssueDate");

                    if (elName) elName.textContent = rec.studentName;
                    if (elEnroll) elEnroll.textContent = rec.enrollmentNo;
                    if (elCertId) elCertId.textContent = rec.certId;
                    if (elEvent) elEvent.textContent = rec.eventTitle;
                    if (elDate) elDate.textContent = new Date(rec.timestamp).toLocaleDateString("en-IN", { dateStyle: "medium" });

                    resultBox.scrollIntoView({ behavior: "smooth", block: "nearest" });
                } else {
                    alert(`Record Verified!\nCandidate: ${rec.studentName}\nID: ${rec.certId}\nAuthentic: ${data.isAuthentic ? "YES" : "TAMPERED"}`);
                }
            } else {
                alert("No authentic record found for ID: " + queryVal);
                if (resultBox) resultBox.style.display = "none";
            }
        } catch (error) {
            console.error("Verification Error:", error);
            alert("Unable to verify document. Please try again.");
        } finally {
            submitBtn.textContent = "Verify Document";
            submitBtn.disabled = false;
        }
    });
}