const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");

const CONTRACT_ADDRESS = "0x28c9c77549F21dfb76834eE91F90EeEA1861F495";
const RPC_URL = "https://ethereum-sepolia-rpc.publicnode.com";
require("dotenv").config();

const PRIVATE_KEY = process.env.PRIVATE_KEY;

if (!PRIVATE_KEY) {
  throw new Error("PRIVATE_KEY is missing from environment variables (.env file).");
}

const ABI = [
  "function anchorBatch(bytes32 batchId, bytes32 merkleRoot, uint256 totalRecords) external",
  "function getBatch(bytes32 batchId) external view returns (bytes32 merkleRoot, uint256 timestamp, uint256 totalRecords)"
];

async function anchorCurrentBatch() {
  const provider = new ethers.JsonRpcProvider(RPC_URL);
  const wallet = new ethers.Wallet(PRIVATE_KEY, provider);
  const contract = new ethers.Contract(CONTRACT_ADDRESS, ABI, wallet);

  // Read payload generated by C++ engine
  const payloadPath = path.join(__dirname, "../batch_payload.json");
  const rawData = fs.readFileSync(payloadPath, "utf8").replace(/^\uFEFF/, "").trim();
  const payload = JSON.parse(rawData);

  const batchIdHash = ethers.id(payload.batch_id);

  const tx = await contract.anchorBatch(batchIdHash, payload.merkle_root, payload.total_records);
  const receipt = await tx.wait();

  // Return standardized schema for Frontend/API
  return {
    success: true,
    batch_id: payload.batch_id,
    batch_id_hash: batchIdHash,
    merkle_root: payload.merkle_root,
    total_records: payload.total_records,
    tx_hash: receipt.hash,
    block_number: receipt.blockNumber,
    explorer_url: `https://sepolia.etherscan.io/tx/${receipt.hash}`,
    timestamp: Math.floor(Date.now() / 1000)
  };
}

module.exports = { anchorCurrentBatch };